/* 
 * Northwind API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using NUnit.Framework;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CategoriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CategoriesApiTests
    {
        private CategoriesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CategoriesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoriesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CategoriesApi
            //Assert.IsInstanceOfType(typeof(CategoriesApi), instance, "instance is a CategoriesApi");
        }

        /// <summary>
        /// Test ApiCategoriesGet
        /// </summary>
        [Test]
        public void ApiCategoriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiCategoriesGet();
            
        }
        /// <summary>
        /// Test ApiCategoriesImageIdGet
        /// </summary>
        [Test]
        public void ApiCategoriesImageIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiCategoriesImageIdGet(id);
            
        }
        /// <summary>
        /// Test ApiCategoriesImagePut
        /// </summary>
        [Test]
        public void ApiCategoriesImagePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CategoryImageModel body = null;
            //var response = instance.ApiCategoriesImagePut(body);
            //Assert.IsInstanceOf<CategoryImageModel> (response, "response is CategoryImageModel");
        }
    }

}
