/* 
 * Northwind API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryImageModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CategoryImageModelTests
    {
        // TODO uncomment below to declare an instance variable for CategoryImageModel
        //private CategoryImageModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CategoryImageModel
            //instance = new CategoryImageModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoryImageModel
        /// </summary>
        [Test]
        public void CategoryImageModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CategoryImageModel
            //Assert.IsInstanceOfType<CategoryImageModel> (instance, "variable 'instance' is a CategoryImageModel");
        }


        /// <summary>
        /// Test the property 'CategoryID'
        /// </summary>
        [Test]
        public void CategoryIDTest()
        {
            // TODO unit test for the property 'CategoryID'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Test]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }

    }

}
