/* 
 * Northwind API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateProductModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateProductModelTests
    {
        // TODO uncomment below to declare an instance variable for UpdateProductModel
        //private UpdateProductModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateProductModel
            //instance = new UpdateProductModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateProductModel
        /// </summary>
        [Test]
        public void UpdateProductModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateProductModel
            //Assert.IsInstanceOfType<UpdateProductModel> (instance, "variable 'instance' is a UpdateProductModel");
        }


        /// <summary>
        /// Test the property 'ProductID'
        /// </summary>
        [Test]
        public void ProductIDTest()
        {
            // TODO unit test for the property 'ProductID'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'QuantityPerUnit'
        /// </summary>
        [Test]
        public void QuantityPerUnitTest()
        {
            // TODO unit test for the property 'QuantityPerUnit'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitsInStock'
        /// </summary>
        [Test]
        public void UnitsInStockTest()
        {
            // TODO unit test for the property 'UnitsInStock'
        }
        /// <summary>
        /// Test the property 'UnitsOnOrder'
        /// </summary>
        [Test]
        public void UnitsOnOrderTest()
        {
            // TODO unit test for the property 'UnitsOnOrder'
        }
        /// <summary>
        /// Test the property 'ReorderLevel'
        /// </summary>
        [Test]
        public void ReorderLevelTest()
        {
            // TODO unit test for the property 'ReorderLevel'
        }
        /// <summary>
        /// Test the property 'Discontinued'
        /// </summary>
        [Test]
        public void DiscontinuedTest()
        {
            // TODO unit test for the property 'Discontinued'
        }
        /// <summary>
        /// Test the property 'SupplierID'
        /// </summary>
        [Test]
        public void SupplierIDTest()
        {
            // TODO unit test for the property 'SupplierID'
        }
        /// <summary>
        /// Test the property 'CategoryID'
        /// </summary>
        [Test]
        public void CategoryIDTest()
        {
            // TODO unit test for the property 'CategoryID'
        }

    }

}
