/* 
 * Northwind API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CategoryImageModel
    /// </summary>
    [DataContract]
        public partial class CategoryImageModel :  IEquatable<CategoryImageModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryImageModel" /> class.
        /// </summary>
        /// <param name="categoryID">categoryID (required).</param>
        /// <param name="picture">picture.</param>
        public CategoryImageModel(int? categoryID = default(int?), byte[] picture = default(byte[]))
        {
            // to ensure "categoryID" is required (not null)
            if (categoryID == null)
            {
                throw new InvalidDataException("categoryID is a required property for CategoryImageModel and cannot be null");
            }
            else
            {
                this.CategoryID = categoryID;
            }
            this.Picture = picture;
        }
        
        /// <summary>
        /// Gets or Sets CategoryID
        /// </summary>
        [DataMember(Name="categoryID", EmitDefaultValue=false)]
        public int? CategoryID { get; set; }

        /// <summary>
        /// Gets or Sets Picture
        /// </summary>
        [DataMember(Name="picture", EmitDefaultValue=false)]
        public byte[] Picture { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CategoryImageModel {\n");
            sb.Append("  CategoryID: ").Append(CategoryID).Append("\n");
            sb.Append("  Picture: ").Append(Picture).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CategoryImageModel);
        }

        /// <summary>
        /// Returns true if CategoryImageModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CategoryImageModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CategoryImageModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CategoryID == input.CategoryID ||
                    (this.CategoryID != null &&
                    this.CategoryID.Equals(input.CategoryID))
                ) && 
                (
                    this.Picture == input.Picture ||
                    (this.Picture != null &&
                    this.Picture.Equals(input.Picture))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CategoryID != null)
                    hashCode = hashCode * 59 + this.CategoryID.GetHashCode();
                if (this.Picture != null)
                    hashCode = hashCode * 59 + this.Picture.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
